### ISSUE TITLE
property order for multiple_prop PTs

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#102]
It would be good to have and understand ‘rules’ for the ordering of properties in multiple_prop PTs. (It isn’t currently very clear how ordering is created for the options in a PT—I believe it has to do with the document-order in which properties appear in RDA-Vocabularies RDF/XML and the way that the recursive templates processes these.)

If possible**, the following are desirable:

- Property order in multiple-property PTs is the same for the given PT in the Sinopia RT, in the property-list sub-list at the top of the HTML RT, and in the PT details section in the HTML RT
- Property order follows some ‘rule’, for example, they are ordered by P-number, they are ordered alphabetically by English-language label, etc.

I asked @cspayne whether meeting the above bulleted requirements would be possible. But the more I think about it, I realize that this depends on mostly (all?) XSLT processing, not Python processing (but Python code for eliminating duplicate prop IRIs is related somewhat). I need to look at stylesheets and follow up. 

CC @pan-zhuo

**Comment by briesenberg07** [comment]
Preference for @pan-zhuo would be to present alphabetically by English-language element name

**Comment by cspayne** [comment]
multiple_prop PTs are now alphabetical in Sinopia and html templates!
