### ISSUE TITLE
Subprops of "Expression: has form of notation" missing from HTML hierarchical display

### ISSUE THREAD

**Issue by pan-zhuo** [uwlib-cams/sinopia_maps#110]
Subprops of "Expression: has form of notation" include:

Expression: form of musical notation

Expression: form of notated movement

Expression: form of tactile notation

Expression: script

**Comment by briesenberg07** [comment]
None of the subproperties above are showing!

**Comment by briesenberg07** [comment]
Could be related to #94

**Comment by cspayne** [comment]
solved in [this map_storage commit](https://github.com/uwlib-cams/map_storage/commit/b73071e93b6cf60a3aa11edaca496cb056bdc99b)
