### ISSUE TITLE
update HTML templates

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#113]
# TO DO list
## uwsinopia.xsd
- [x] Implement additional guidance features, see @pan-zhuo 's [PT Guidance draft](https://docs.google.com/document/d/1s7wBUa525j4h8RYV0BON1UBPVHW3NiZJpxOUF3Jx4Fc/edit?usp=sharing)
- [x] Implement validation for `guidance_set rt_id` attribute, set default to 'default' 
   - [x] Includes, create stylesheet to populate `rt_id` enumerations from sinopia_maps.xml

## prop_set-to-HTML stylesheets
- [x] Output guidance content to detail for each PT; for details about content in prop_sets which will need to be processed, see:
   - guidance_set [xsd definition](https://github.com/uwlib-cams/sinopia_maps/blob/79efd8f6919ae16f6e7cd4e6ba24f7b2b882145d/xsd/uwsinopia.xsd#L40-L163)
   - Notes on new elements in [DRAFT_guidance_set](https://docs.google.com/document/d/1s7wBUa525j4h8RYV0BON1UBPVHW3NiZJpxOUF3Jx4Fc/edit?usp=sharing)
   - *For one method of storing guidance_set content matching a given RT ID for processing, see [004ref_01_prop_set_to_html.xsl](https://github.com/uwlib-cams/sinopia_maps/blob/79efd8f6919ae16f6e7cd4e6ba24f7b2b882145d/xsl/004ref_01_prop_set_to_html.xsl#L36-L236) and [004ref_03_pt_detail.xsl](https://github.com/uwlib-cams/sinopia_maps/blob/79efd8f6919ae16f6e7cd4e6ba24f7b2b882145d/xsl/004ref_03_pt_detail.xsl)*
- [x] Use \@localid_implementation_set as IDs for navigating and linking to details for a specific PT in a specific HTML RT; existing stylesheets create different ids--they don't use localids--at multiple locations in existing stylesheets
   - when [creating li/a/href](https://github.com/uwlib-cams/sinopia_maps/blob/79efd8f6919ae16f6e7cd4e6ba24f7b2b882145d/xsl/004_01_storage_to_html.xsl#L429-L436) in the overall RT property list
   - when creating [heading ids for PT detailed info](https://github.com/uwlib-cams/sinopia_maps/blob/79efd8f6919ae16f6e7cd4e6ba24f7b2b882145d/xsl/004_01_storage_to_html.xsl#L537-L540), etc.
- [x] Add additional information to PT details
   - [x] Account for alt_pt_labels in property list, PT details
   - [x] PT attribute user ID default, date default
   - [x] Literal validation options
   - [x] Default values if any (see #118 )
   - [x] See .wiki/[author_07_property_templates](https://github.com/uwlib-cams/sinopia_maps/wiki/author_07_property_templates) for additional PT config info which may be helpful to output to HTML as reference
- [x] Provide a Toolkit link and Registry link for each property in a multi-prop PT, in RT property list, PT detail, or both
- [x] Update HTML RTs to align with current naming conventions (we no longer use 'WAU RT RDA [...]' in RT IDs)
- [x] Output CC-zero dedication footer which includes attribution to RDA Registry (use webviews/xsl/CC0-footer.xsl > [CC0-footer-rda-pages](https://github.com/uwlib-cams/webviews/blob/91a32640cb697e7118f90e7304864d5181840ed6/xsl/CC0-footer.xsl#L58-L114)

## stylesheets for prop_set processing 
- [ ] Update prop_set-to-RDFXML-RT stylesheet output for remarkURL values: link to property template in the HTML RT (\@localid_implementation_set)

## Other
- [ ] [?] Add link to HTML RTs for opening issue (add link to each PT? Possible to autopopulate issue with PT ID?)

**Comment by cspayne** [comment]
@briesenberg07 @pan-zhuo 
The updated HTML templates are live at https://uwlib-cams.github.io/sinopia_maps/

**Comment by cspayne** [comment]
**HTML templates updated.** 

notes on the final two tasks:
Update prop_set-to-RDFXML-RT stylesheet output for remarkURL values: link to property template in the HTML RT (@localid_implementation_set) - _see issue #46 in map_storage_
Add link to HTML RTs for opening issue (add link to each PT? Possible to autopopulate issue with PT ID?) - _determined not a priority for now_
