### ISSUE TITLE
Display original PT label when alternate label is used in HTML

### ISSUE THREAD

**Issue by pan-zhuo** [uwlib-cams/sinopia_maps#115]
It appears that when an alt label is used, the original label will not be shown in HTML.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/100716525/234467243-a76bfa2b-99ad-4a18-bee2-226060d2c62f.png">

I think the following would make more sense:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/100716525/234467493-3b3b06b1-7fcb-49e2-a33c-aea944132f20.png">

@briesenberg07

**Comment by cspayne** [comment]
done in updated prop_set_to_html style sheets
