### ISSUE TITLE
add diagrams to guidance on aggregates

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#128]
### Describe the issue

@pan-zhuo I'd like to add your diagrams from our 2023-05-25 presentation to the guidance documentation on aggregates. *Would you allow this use?* I might modify the slides some (perhaps remove the "analytical description" and other language taken from Original RDA).

See:
- guidance document [Pre-cataloging decisions: choosing templates for describing aggregates](https://uwlib-cams.github.io/sinopia_maps/md/describing_printMonograph_aggregates)
- [2023-05-25_Sinopia_templates_official_RDA.pdf](https://uwnetid.sharepoint.com/:b:/s/og_library_cams/EQ3lSmnK-KFHlOWudYmXwr8BTo6xqDeVtovcHMnNvFuDiQ?e=NCD8te) slides 13-16

**Comment by pan-zhuo** [comment]
Feel free to use and adapt them @briesenberg07 ! Honestly I didn't have too much time to create the diagrams so they could use a lot of improvement.
