### ISSUE TITLE
disallow repeatable + ordered PTs

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#129]
as of 2023-06-06, repeatable and ordered property templates in Sinopia use a blank-node structure to create an ordered list of values:

```
<resource> <prop> _:01 .
_:01 rdf:first "value 01" ;
   rdf:rest _:02 .
_:02 rdf:first "value 02" ;
   rdf:rest rdf:nil .
```

*Related to https://github.com/uwlib-cams/sinopia_maps/discussions/127*

**Comment by briesenberg07** [comment]
Hello @pan-zhuo \:

This is a somewhat alarming turn of events, as I believe the *order* of subject values is important. I had not realized that using repeating, ordered values would create such data, but @junghaelee and I realized this recently. 

I'm not sure how we can create ordered subject values at this time...

**Comment by pan-zhuo** [comment]
I guess we will just have to avoid using 'ordered' for the moment. I will comment them out in the prop_sets.

**Comment by briesenberg07** [comment]
Thank you @pan-zhuo !
