### ISSUE TITLE
Show 'main' property label in PT property dropdown

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#134]
Not sure why no label shows for 'main' prop in PT. Assume some change is needed in prop_set-to-RDF/XML-template stylesheets...

![image](https://github.com/uwlib-cams/sinopia_maps/assets/27664966/cad96e2f-3a34-48db-9ed7-e8b739efcb65)

**Comment by cspayne** [comment]
this was an error in the fix_duplicate_triples function in 001_output_publish_load.py - now corrected
