### ISSUE TITLE
change heading 'Guidance and Configuration' to 'Guidance' or similar

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#137]
Heading above guidance content will only appear if guidance content is present...

![image](https://github.com/uwlib-cams/sinopia_maps/assets/27664966/4a00a971-1c44-4c4a-a080-086f0c2b647d)

![image](https://github.com/uwlib-cams/sinopia_maps/assets/27664966/3594350c-7fcd-4a4e-b508-6ce0e2bba693)

...but configuration info will always appear.

Use 'Guidance' or similar, ensure new heading isn't too small + inconspicuous to see clearly when browsing HTML RTs)

**Comment by cspayne** [comment]
Some options: 
![Screenshot 2023-06-26 104909](https://github.com/uwlib-cams/sinopia_maps/assets/48925631/c3944da0-1404-4a58-9ebf-f8cc666685fc)
![Screenshot 2023-06-26 104957](https://github.com/uwlib-cams/sinopia_maps/assets/48925631/390f709e-4c07-4b99-be26-0a1e8710708b)

if there's another heading you want to try let me know!
