### ISSUE TITLE
eliminate guidance heading when no guidance exists

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#138]
See empty guidance heading in [HTML PT](https://uwlib-cams.github.io/sinopia_maps/html/UWSINOPIA_WAU_rdaWork_printMonograph_CAMS.html#uwmaps_rdaw_p10k_wP10365_is_d2e2564)

![image](https://github.com/uwlib-cams/sinopia_maps/assets/27664966/fec3334f-2d9d-4d3d-91a3-e7169339b449)

**Comment by cspayne** [comment]
this occurred when the guidance_set was present but contained no default and no elements matching the rt_id - now resolved by checking if the guidance_set node is empty after being retrieved from the prop_set
