### ISSUE TITLE
Include only person, corporate body, and family properties in resource templates

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#141]
### Resource Template Label or ID

multiple

### Problem using the resource template, or request a change

Include only person, corporate body, and family properties in resource templates

### Any other relevant details

Discussion from 2023-06-29:

Why are we offering agent and collective agent properties? These property options should be removed where they appear in templates 
- Person, corporate body, and family will only be used, this is basic cataloging 
- Including these properties was the easiest way to author templates – using subproperty relationships to provide the options 
- Could the agent and collective agent properties be removed from display, while still allowing to use the `all_subprops` or `all_all_subprops` options in prop_sets?? 
- Possibly, we possibly will need to enter specific properties for a property selection

**Comment by cspayne** [comment]
@briesenberg07 
looking at map_storage 001_01_build_update.xsl, 001_02_source_templates.xsl, and sinopia_maps 001_05_multiple_properties.xsl, editing 001_02_source_templates.xsl to only select agent properties with the proper domains (for person, corporate body, and family) to appear in the agent propset should not affect multiprops, which pulls subproperties from the RDA-Vocabularies xml files.

**Comment by cspayne** [comment]
that is, if I am understanding the issue correctly and we want only person, corporate body, and family properties available in the agent prop_set

**Comment by briesenberg07** [comment]
Hello @cspayne 
The change that is requested is that properties which create a relationship from a W|E|M|I to an agent of some kind be limited to those which would create a relationship to either a person, corporate body, or family.

So for example the following changes would be made in the [has artist agent](https://uwlib-cams.github.io/sinopia_maps/html/UWSINOPIA_WAU_rdaWork_printMonograph_CAMS.html#uwmaps_rdaw_p10k_wP10058_is_d2e374) PT:

- has artist agent (we might create an alt PT label like 'has artist person, corporate body, or family')
   - ~~has artist agent~~
   - ~~has artist collective agent~~
   - has artist corporate body
   - has book artist corporate body
   - has calligrapher corporate body
   - has sculptor corporate body
   - has artist family
   - has book artist family
   - has calligrapher family
   - has sculptor family
   - ~~has book artist collective agent~~
   - ~~has calligrapher collective agent~~
   - ~~has sculptor collective agent~~
   - has artist person
   - has book artist person
   - has calligrapher person
   - has sculptor person
   - ~~has book artist agent~~
   - ~~has calligrapher agent~~
   - ~~has sculptor agent~~

I believe that filtering could take place based on the [`rdfs:range`](http://www.w3.org/2000/01/rdf-schema#range) of W|E|M|I properties, but this seems tricky because only the object properties have a range, not canonical properties.

**Comment by pan-zhuo** [comment]
Or just filter on the label 'agent'?

**Comment by cspayne** [comment]
that was my next thought - during output_publish_load, properties could be checked and all 'agent' properties filtered out based on label.

**Comment by briesenberg07** [comment]
That seems reasonable... I suppose we can count on the RDA element labels being very consistent, and relationship elements with agent or collective agent always saying so (including 'agent') in the title.

Would a post-processing fix like this cause any problems when the 'main' PT property - the prop element in a prop set - which is used to create the property template is one of the properties which is filtered out? 

I don't think so, as the PT description blank node just includes a list of `sinopia:hasPropertyUri` triples.

**Comment by briesenberg07** [comment]
It's too bad I didn't realize this earlier! Didn't even think about the fact that catalogers never describe generalized agents or collective agents. I might've implemented all_subprops and all_all_subprops differently if so.

**Comment by cspayne** [comment]
To do:
- [ ] filter out agent props in 001_output_publish_load.py
- [ ] filter out agent props in html rts

**Comment by cspayne** [comment]
see [filter out agent props in multiprops commit](https://github.com/uwlib-cams/sinopia_maps/commit/915dbede757141dce378702ee155a9d36d96e781)

**Comment by cspayne** [comment]
see (remove agent subprops from html)[https://github.com/uwlib-cams/sinopia_maps/commit/2e9678e273357731698c0a8306e58d22e4b82e85]
