### ISSUE TITLE
Should WEMI-linking properties be required?

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#145]
### Discussed in https://github.com/uwlib-cams/sinopia_maps/discussions/130

<div type='discussions-op-text'>

<sup>Originally posted by **briesenberg07** June 13, 2023</sup>
Currently WEMI-linking properties are required in Sinopia RDA/RDF templates. However, this means catalogers much use a workaround in order to save work, entering fake IRIs for (related) resource B, so that they can save resource A, add IRI for resource A to resource B, save resource B, then go back to resource A and replace fake with actual IRI.

**PROS AND CONS**
| PRO | CON |
|---|---|
| Setting properties as required in templates aligns with RDA Toolkit [guidance on minimum description of a resource entity](https://access.rdatoolkit.org/en-US_ala-f4fb013b-b64e-37b1-902c-561d27b1e832) | Setting properties as required makes a workaround neccessary and increases complexity of cataloging |
| Setting properties as required ensures that relationships between WEMI resources will be created | Because fake IRIs must be entered at some point initially in order to save a resource and proceed with description, false relationships to nonexistent entities may be created |
| ... | ...|

</div>

**Comment by cspayne** [comment]
@briesenberg07 @gerontakos @AdamSchiff @CECSpecialistI @JianPLee @junghaelee 

One option is to implement the default URI element within the property template and include guidance to remind catalogers that the URI should be replaced once related WEMI resources are created. 
The default URI element would auto-fill the WEMI-linking properties with a placeholder URI which could be replaced once a URI is generated. 
Each placeholder URI would be the same, making it easy to search resources and find any URI that needs replacing, while allowing resources to be saved before the related WEMI resources are created.

**Comment by briesenberg07** [comment]
Thank you @cspayne 
CC @gerontakos @AdamSchiff @CECSpecialistI @JianPLee @junghaelee

I mocked this up in a test template for RDA entity, which can be found in Stage, to show what it would look like and how it would work.

> **UWSINOPIA WAU rdaEntity test test**

The default/'placeholder' IRI and IRI label appear when the template is opened:
![image](https://github.com/uwlib-cams/sinopia_maps/assets/27664966/7fe7f37a-7ed7-4b4c-9775-aa2d68194f52)

When the needed resource IRI is available, the default value must be deleted:
![image](https://github.com/uwlib-cams/sinopia_maps/assets/27664966/d9025a10-15aa-4a84-8515-3b1e277a74d2)

And the lookup can then be used to retrieve it:
![image](https://github.com/uwlib-cams/sinopia_maps/assets/27664966/671b7b55-1ed7-4108-b55a-0b7e8923a4da)


On further thought @cspayne if we do this I'd like to use a placeholder IRI label more like 'USE LOOKUP TO REPLACE THIS IRI'

**Comment by briesenberg07** [comment]
From [discussion](https://github.com/uwlib-cams/sinopia_maps/discussions/130#discussioncomment-6734064):

> - configure default something like 'https://FAKE_EXPRESSION_REPLACE_ME' for each WEMI-linking property
> - add PT remark like 'REMEMBER to replace the filler IRI for [W/E/M/I] once IRI is available!'

**Comment by briesenberg07** [comment]
@cspayne stated:

> Each placeholder URI would be the same, making it easy to search resources and find any URI that needs replacing, while allowing resources to be saved before the related WEMI resources are created.

...perhaps better to use the ***same*** 'dummy' IRI for all props, instead of what I suggest above? What do you think @cspayne ?

**Comment by cspayne** [comment]
> @cspayne stated:
> 
> > Each placeholder URI would be the same, making it easy to search resources and find any URI that needs replacing, while allowing resources to be saved before the related WEMI resources are created.
> 
> ...perhaps better to use the _**same**_ 'dummy' IRI for all props, instead of what I suggest above? What do you think @cspayne ?

I think that could be beneficial for any sort of search-and-replace a cataloger might want to do to speed up the process.

**Comment by briesenberg07** [comment]
Agreed 👍 let's do that!

**Comment by cspayne** [comment]
![Screenshot 2023-08-15 150204](https://github.com/uwlib-cams/sinopia_maps/assets/48925631/2c0e9f2f-033e-41ad-a1b5-971f1a03c21a)

@briesenberg07 how does this look?

**Comment by briesenberg07** [comment]
I think it looks great! Thank you!
