### ISSUE TITLE
implement UW RDA Extension 'has creator characteristic'

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#148]
### Resource Template Label or ID

RDA Work templates

### Problem using the resource template, or request a change

Implement property https://doi.org/10.6069/uwlib.55.d.4#hasCreatorCharacteristic as follows:

- If possible, configure lookup to LCDGT
- If no lookup available, configure as URI PT with guidance to use [LCDGT via id.loc.gov](https://id.loc.gov/authorities/demographicTerms.html)

**Comment by cspayne** [comment]
@briesenberg07 
Should this property template appear in both rdaWork printMonograph and rdaWork aggregating_printMonograph, or just the former?

**Comment by briesenberg07** [comment]
Let's only implement in **rdaWork printMonograph** for now. 

This is connected to the RDA model, in that an [aggregating work](https://access.rdatoolkit.org/en-US_ala-bd1f1ef9-978c-34ee-8881-acc1500130b9/section_bmb_j23_m2b) is a plan to select and arrange expressions and embody them in a single manifestation. Thus, the creator(s) for an aggregating work would not be the same as authors or other creators of the works aggregated. They would be more like, for example, the editors of anthologies.

Because of this I don't imagine that creator characteristics are as important to users for *aggregating* works as for *aggregated* works. I could be wrong, but let's hold off on implementing in the aggregating_printMonograph RT until/unless the testing group indicates that this property is needed there.
