### ISSUE TITLE
configure 'has location of item' property template

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#150]
We began discussing the 'has location of item' property template on 2023-07-18. Planning to use a Wikidata lookup to retrieve IRIs for items which are instances of physical location.

On Wikidata, items, @AdamSchiff says:

> I added a few more statements to the item for Suzzallo and Allen Libraries Stacks: https://www.wikidata.org/wiki/Q120734816
> There's the "code" property that I used for the location code.
> If we want to go this way so that Sinopia can do a lookup in Wikidata, we'll need to create a 326 items for all the codes that we use.
> The broad list of codes for library buildings used in Alma is at https://staff.lib.uw.edu/operations/arcs/for-arcs-staff/alma-record-standards/physical-inventory/holdings-records/alma-library-and-location-codes
> For specific locations, there is a list of the most used codes at https://staff.lib.uw.edu/operations/cas/for-all-staff/management/location-codes.  And the comprehensive list is a spreadsheet: https://staff.lib.uw.edu/operations/cas/for-all-staff/management/alma-location-codes.xlsx.
> I've created a second item for CAMS stacks: https://www.wikidata.org/wiki/Q120734968
> Can you think of any other properties that we would want to include in these items if we do go this route?

Thank you Adam!

**Comment by briesenberg07** [comment]
OPTIONS

1. Create Wikidata items for item locations (see [Suzzallo and Allen Libraries Stacks](http://www.wikidata.org/entity/Q120734816)). Configure property templates as Wikidata lookup.
2. Create a local UWLSWD vocabulary for item locations. Configure property templates as IRI/label entry, providing remark in RT and possibly additional guidance.

Any thoughts on which makes the most sense?
Any other options? 
@AdamSchiff @CECSpecialistI @gerontakos @cspayne @pan-zhuo @junghaelee @JianPLee

**Comment by briesenberg07** [comment]
ANOTHER OPTION

3. Create UWLSWD vocabulary for item locations. Configure property template as literal, with guidance to enter location notation (i.e. 'szstx') as string.

**Comment by CECSpecialistI** [comment]
ANOTHER OPTION

4. Configure property template as literal, with guidance to enter location notation as string. Don't mint any IRI's for locations or sublocations until implementation.

**Comment by AdamSchiff** [comment]
We wouldn't want to display just a code as the location in a discovery system, so I think having a URI that leads to a more clear label may be better than just a literal code value.  Although, it's the code that we use now and Primo can turn that into something else in display, so maybe a literal is sufficient?  How would it work at the time of discovery?

Adam

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***
________________________________

**Comment by AdamSchiff** [comment]
I've created nearly a dozen items for some of our locations, to gain some idea of what they'd look like in Wikidata:

[cid:9604922f-2d22-4a06-b843-cf3043426208]

https://www.wikidata.org/wiki/Q120734816
https://www.wikidata.org/wiki/Q120734968
https://www.wikidata.org/wiki/Q120735195
https://www.wikidata.org/wiki/Q120735283
https://www.wikidata.org/wiki/Q121087891
https://www.wikidata.org/wiki/Q121088067
https://www.wikidata.org/wiki/Q121088103
https://www.wikidata.org/wiki/Q121088143
https://www.wikidata.org/wiki/Q121088150
https://www.wikidata.org/wiki/Q121088155
https://www.wikidata.org/wiki/Q121088164

When there are many codes for one of our libraries, I figured out that I could use the "Duplicate this item" link in Wikidata to derive a new item and make just a few changes to it for each location.  So I was able to create a bunch of Tateuchi items fairly quickly.  Of course if we decided to use Wikidata, I'm sure Crystal could create a spreadsheet to use with QuickStatements to generate items for all of our codes rather quickly.

Although I doubt these items would be changed by other Wikidata users, it's certainly possible for that to happen, so maintaining our own list somewhere to use in Sinopia is probably a better option.

Adam

Adam L. Schiff
Principal Cataloger
University of Washington Libraries
(206) 543-8409
***@***.***
________________________________

**Comment by briesenberg07** [comment]
> How would it work at the time of discovery?

The $1,000,000 question. My answer is that I don't know because I'm not building any discovery systems right now. That's not a reason to attempt and create data that we think will work well in discovery systems! 

🤔 Are there any general-purpose linked data modeling guidelines which exist which could help making decisions such as this? Probably people have all kinds of opinions? Could be a question to pose to the LD4 Discovery Affinity Group. 

Do we simply go with 'things, not strings'?

**Comment by CECSpecialistI** [comment]
I have no idea how to even approach the decision between these options. Will holdings data in a linked data cataloging environment also be linked data? Or, will discovery systems configure it in some other way? Maybe the LD4 Discovery Affinity Group would have some insights. Or, since Adam has already done the Wikidata leg work, maybe we should go with that option and see how it works? I don't know that we can make a right or wrong choice at this point.

**Comment by briesenberg07** [comment]
> What is the advantage of having IRI over literal values for location codes?

@JianPLee this is a good question. There are all of the basic linked-data arguments for using IRIs over literals\*\*. But without knowing about a specific discovery system where this data will be loaded I don't think we can know whether literal identifiers or IRIs would work better for our data.

\*\*like
- Linked Data: Evolving the Web into a Global Data Space > [2.2 Naming Things with URIs](http://linkeddatabook.com/editions/1.0/#htoc10)
- 23 Linked Data Things > [Thing 2. RDF and URIs](https://minitex.umn.edu/services/digital-initiatives-metadata/23-linked-data-things/thing-2-rdf-and-uris)
- ... ...
