### ISSUE TITLE
group property dropdowns by class of object, not by nature of relationship

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/sinopia_maps#151]
Mock up one or two ‘relationship to person’, ‘relationship to [RDA Entity here]’ PTs to see what this would look like.

**Comment by cspayne** [comment]
@briesenberg07 @gerontakos @AdamSchiff @CECSpecialistI @JianPLee @junghaelee @pan-zhuo 
See [UWSINOPIA:WAU:rdaWork:test:cspayne](https://stage.sinopia.io/editor/UWSINOPIA:WAU:rdaWork:test:cspayne) in Sinopia Stage for mock-ups of property templates based on class of object.

**Comment by briesenberg07** [comment]
Thank you for creating something for everyone to take a look at @cspayne !
They are indeed ***mega*** property templates!

![![image](https://github.com/uwlib-cams/sinopia_maps/assets/27664966/6e1fcf55-79f9-409e-abc9-284ff3cea250)](https://github.com/uwlib-cams/sinopia_maps/assets/27664966/0d925ebe-556d-42ae-acdc-cc436f5ee10e)

**Comment by briesenberg07** [comment]
🎉 🎉 🎉
