### ISSUE TITLE
Determine best way to organize drop-down property templates 

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/sinopia_maps#154]
Ideas brought up in meeting 8/8/2023:
- Could they be alphabetized, skipping initial ‘is’ or ‘has’? 
   This would result in an alphabetized list where ‘is’ / ‘has’ are mixed 
-  Strip initial ‘has’ / ‘is’ ? 
- use toolkitLabel , instead of rdfs:label ?

**Comment by cspayne** [comment]
@briesenberg07 I just re-uploaded templates to Sinopia with drop-downs sorted skipping the initial 'is' and 'has' to explore this option.

**Comment by briesenberg07** [comment]
So fast! How'd you do it?

**Comment by cspayne** [comment]
It's just some string parsing while the labels are being processed for sorting. 
It splits the label after the first space character, which drops the 'has' or 'is' from the string. 

```python
value_keyword = value.split(" ", 1)[1]
```
