### ISSUE TITLE
storage_to_rdfxml not set up to handle non RDA multi-props

### ISSUE THREAD

**Issue by cspayne** [uwlib-cams/sinopia_maps#162]
Current code in 001_05_multiple_properties.xsl

```xsl
<!-- when - for other-ontology PTs (TO DO LATER or never) -->
<xsl:otherwise>
     <xsl:text>ERROR - MULTIPLE-PROPERTY PTs NOT CONFIGURED FOR THIS SOURCE</xsl:text>
</xsl:otherwise>
```

**Comment by briesenberg07** [comment]
I [see it](https://github.com/uwlib-cams/sinopia_maps/blob/678f42ca880922c06aef9eb021525cadd4d698ed/xsl/001_05_multiple_properties.xsl#L102) now!

Looks like currently (pseudo-code):

```
for multiple props:
   when RDA:
      when property_selection:
         ...
      when all_subprops:
         ...
      when all_all_subprops:
         ...
   else:
      x error
```

what about:

```
for multiple props:
   when RDA:
      when property_selection:
         ...
      when all_subprops:
         ...
      when all_all_subprops:
         ...
   when UW RDA Ext:
      when property_selection:
         ...
      else:
         x error
   else:
      x error
```

But wait! It isn't that easy! because... What if property_selection is used in an RDA prop element, and some UW RDA Ext properties are selected? What if property_selection is used in a UW RDA Ext prop element, and some RDA properties are selected!? Ack

**Comment by cspayne** [comment]
I think we could do something like: 
```
for multiple props:
when RDA or UW RDA ext:
      when RDA and all_subprops: (do uw rda extension props have subprops?)
         ...
      when RDA and all_all_subprops:
         ...
      when property_selection:
         when subprop iri starts with "http://rdaregistry":
               get subprop info from set_source
         when subprop iri starts with "https://doi.org/10.6069/uwlib.55.d.4:
              get subprop info...
          else:
               x error
      else:
          x error
else: 
    x error
```

(although I believe we'd need a way to determine the RDA set source for each sub property in the case of a UW RDA Ext prop with RDA subprops)

**Comment by briesenberg07** [comment]
Thank you @cspayne , adding comments to [your plan above](https://github.com/uwlib-cams/sinopia_maps/issues/162#issuecomment-1681184029): 
```
for multiple props:
  when RDA or UW RDA ext:
      when RDA and all_subprops: 
      # @cspayne asks do uw rda extension props have set subprops that can be selected 
      # through all or all_all_subprops?
         # BMR: No subprop relationships currently exist in UW RDA Ext, no need to code for that
         ...
      when RDA and all_all_subprops:
         ... # BMR: as above, no subprop relationships in UW RDA Ext at this time, no need to code for it
      when property_selection:
         when subprop iri starts with "http://rdaregistry": 
         # BMR: does 'subprop' here = selected prop? Then yes, 
               retrieve subprop info from RDF/XML at get_prop_sets/get_set/set_source URL
         when subprop iri starts with "https://doi.org/10.6069/uwlib.55.d.4:
         # @cspayne asks where to get subprop info...
         # BMR: I don't think we need anything that isn't in the property_selection element
         # This has IRI, label, and lang tag
         # if we do, get from RDF/XML at get_prop_sets/get_set/set_source URL, as for RDA props. but I don't think we need to
            pull property options from information in `property_selection`
         else: # so, if property_selection, but IRI doesn't match pattern for either RDA or UW RDA Ext
               x error
      else:
          x error
else: 
    x error
```
I think it's a good plan. I want to confirm the following:

1. Under `when property_selection:` above, do you use 'subprop' to mean the entered selected properties?
2. `when subprop (selected prop?) IRI starts with 'https://doi.org/10.6069/...'` I don't think we need any information about the UW RDA Ext props that isn't either in the `property_selection` element (property label, lang tag, and IRI are there) or the implementation set (PT type and config details). So we should have what we need in the prop_set without going to the UW RDA Ext RDF/XML. I just don't think the current stylesheets are written to get what is needed.
3. To comment in code: *Can't implement all_subprops or all_all_subprops in a UW RDA Ext `prop` element*

Does this help? I could meet tomorrow afternoon, or Friday, to discuss in detail if that would be helpful.

**Comment by cspayne** [comment]
>  1. Under when property_selection: above, do you use 'subprop' to mean the entered selected properties?

Yes. I realize now that all of the information for the selected properties when using property selection is available within the given prop_set, so I don't think accessing the online rda set_source is necessary in the case of property selection. (Although perhaps we should note somewhere that this is how property selection works, because it means that any human errors in entering the correct prop iri and label will not be caught)

>  2. when subprop (selected prop?) IRI starts with 'https://doi.org/10.6069/...' I don't think we need any information about the UW RDA Ext props that isn't either in the property_selection element (property label, lang tag, and IRI are there) or the implementation set (PT type and config details). So we should have what we need in the prop_set without going to the UW RDA Ext RDF/XML. I just don't think the current stylesheets are written to get what is needed 

Yes that makes sense. 

>  3. To comment in code: Can't implement all_subprops or all_all_subprops in a UW RDA Ext prop element

This can also be a comment in the wiki as well!

**Comment by briesenberg07** [comment]
Agree with all above.  
It's very true, using the `property_selection` element is dependent on accurate human data-entry 😅
