### ISSUE TITLE
Add RDA Toolkit links as remark URL values to props with implementation sets

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#30]
**SOME NOTES:**
- This would ideally be as easy to run as [002_localid_implementation_set.xsl](https://github.com/uwlib-cams/map_storage/blob/main/xsl/002_localid_implementation_set.xsl), the transformation scenario for which is set in the map_storage > .xpr file allowing for easy addition of localids during work in a prop_set instance.

- *However*, [the data source](https://www.rdaregistry.info/Aligns/alignRDA2TK.html) is CSV (unless this information is available in another format that I don't know about). I've never processed CSV with XSLT so I'm not sure whether/how much challenge this will present to writing this as a stylesheet.

- *(It's somewhat less important to note that)* this procedure may need to change in future. For example, if there is a need to provide UW-local guidance, remarks, or other PT-related content in future, remark URL may be used to provide a link to an HTML representation of the property template which would include such guidance alongside the Toolkit link.

**Comment by briesenberg07** [comment]
Tagging @mcm104 ; we discussed at our [07-18 meeting](https://uwnetid.sharepoint.com/:w:/r/sites/og_library_cams/Shared%20Documents/sinopia_maps/meetings/[2022_meetings.docx](https://uwnetid.sharepoint.com/:w:/r/sites/og_library_cams/Shared%20Documents/sinopia_maps/meetings/2022_meetings.docx?d=w94b01f52b4fb4ae084d55a07dcc93321&csf=1&web=1&e=iOoo9i)?d=w94b01f52b4fb4ae084d55a07dcc93321&csf=1&web=1&e=iOoo9i)

**Comment by mcm104** [comment]
New XSLT added to map_store:
- [003_01_convert_csv_to_xml.xsl](https://github.com/uwlib-cams/map_storage/blob/main/xsl/003_01_convert_csv_to_xml.xsl) (outputs XML to [xml/RDA_alignments.xml](https://github.com/uwlib-cams/map_storage/blob/main/xml/RDA_alignments.xml))
- [003_02_add_toolkit_URLs.xl](https://github.com/uwlib-cams/map_storage/blob/main/xsl/003_02_add_toolkit_URLs.xsl) -- this gets executed along with 002_localid_implementation_set.xsl when you Ctrl+Shift+T on a property set -- this worked on my PC, but I would appreciate if someone else tried on their PC to confirm!

003_02_add_toolkit_URLs.xsl was run on all RDA propsets in map_storage (minus RDA Work, which wouldn't run the transformation due to a validation error from an incomplete implementation set). The URLs for the properties I tried worked, but again, if someone else could test a few to make sure everything is working correctly, that would be great!

@briesenberg07

**Comment by briesenberg07** [comment]
- Pulled changes, including changes to `.xpr`, new transformation scenario associated with most prop_set_rda.* files [1]
- Use RDA Work prop set to test, including an `implementation_set` including a remark_url prior to transformation [2]
- Run the configured transformation scenarios:
   - [PROBLEM A] `uwsinopia:remark_url/@iri` value was replaced, even where it had been present
- Update 003_02_add_toolkit_URLs.xsl: 
```
uwsinopia:remark_url/@iri=text()
```
``` 
uwsinopia:remark_url/@iri
```
- Run the configured transformation scenarios:
   - [PROBLEM A] solved ✔️ 
   - [PROBLEM B] The `implementation_set` I had been editing immediately before running the transform was lost [3]
   - [PROBLEM C] `uwsinopia:implementation_set \@localid[...]` values weren't present following transformation
- Update 003_02 as follows:
```
<xsl:when test="uwsinopia:remark_url/@iri"/>
```
``` 
<xsl:when test="uwsinopia:remark_url/@iri">
     <xsl:copy-of select="."/>
</xsl:when>
```
*This way, the `implementation_set` will be copied over even if a `remark_url` already exists for some reason*

- Run the transformation scenarios:
   - [PROBLEM B] solved ✔️ [4], `implementation_set` was copied over even though a `remark_url/@iri` value existed at time of transformation
   - [PROBLEM C] persists ❌ (but, apparently, wasn't happening for you--I don't see missing `@localid`s in the other prop_sets...)
- Update 003_02 as follows:
```
<xsl:otherwise>
     <uwsinopia:implementation_set localid_implementation_set="">
```
``` 
<uwsinopia:implementation_set localid_implementation_set="{@localid_implementation_set}">
```
- Run the transformation scenarios:
   - [PROBLEM C] solved ✔️ 
   - [PROBLEM D] `@localid_implementation_set` values are overwritten at some point in the transformation scenarios ❌ [5]


[1]
![image](https://user-images.githubusercontent.com/27664966/180585474-d69e50e0-07b6-4f55-8a17-a2b946b3dbcc.png)
[2]
![image](https://user-images.githubusercontent.com/27664966/180585624-7ea74266-3f9f-4ab1-b52e-692beb26eb16.png)
[3]
![image](https://user-images.githubusercontent.com/27664966/180586348-489ee602-c279-4e0c-ab88-4c8f35ad9277.png)
[4]
![image](https://user-images.githubusercontent.com/27664966/180586716-b9d13846-b709-412a-8684-c87d1ab744e0.png)
[5]
![image](https://user-images.githubusercontent.com/27664966/180588984-ceac8e3e-b8b2-4581-be30-c711eb4bb59a.png)

**Comment by briesenberg07** [comment]
See [map_storage commit](https://github.com/uwlib-cams/map_storage/commit/1950f045f165f33355dda9cb905c973ca6609d19) for these changes.

I think that the issue of @localids being overwritten can be put off for now--we don't yet have any use for these, they are just something I thought would be needed at some point (???).

Thank you @mcm104 ! 

Let's use these stylesheets/transformation scenarios as-is for now to add the Toolkit links, as these will be helpful for template users.
