### ISSUE TITLE
PT order should match template order

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#44]
When scrolling through PT details in the [legacy RDA monograph profile](https://uwlib-cams.github.io/sinopia_maps/html/WAU.profile.RDA.monograph.html#profile), order of PTs does not match the order in which they appear in the list for the template.

It would be good for the order to match, so that a user could scroll through the HTML representation of the template and see PTs in the order in which they appear in the Sinopia cataloging form.

**Comment by cspayne** [comment]
unsure if updated style sheets achieve this. Needs testing.

**Comment by cspayne** [comment]
[004_01_prop_set_to_html.xsl](https://github.com/uwlib-cams/sinopia_maps/blob/main/xsl/004_01_prop_set_to_html.xsl#L51) does this
