### ISSUE TITLE
Python for batch-loading RTs

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#50]
This scripting ~~would presumably be helpful to have at some point in future~~ is needed, we've been having trouble getting our script to function as expected--see [current issues below](https://github.com/uwlib-cams/sinopia_maps/issues/50#issuecomment-1464805576).

Requirements ~~might include~~ still haven't changed *that much* since I created this issue in 2022-07, except that as of now we don't need to accommodate any nested-resource PTs:

- ~~Identifying which templates are referenced by others, loading referenced templates before referencing templates (when using Load RDF for RTs, RTs referencing RT IDs which do not exist cannot be loaded; not sure whether/how this would impact batch loading)~~
- When loading an updated RT version, find and delete the existing RT prior to loading updated (feel 99% confident we can't load an RT with the same ID as an existing RT)
- Select a platform for loading templates; this would [change generation of RT IRIs](https://github.com/uwlib-cams/sinopia_maps/blob/228f7617ce5770d256a3f278e3523e80fb235b58/xsl/001_02_rt_metadata.xsl#L73-L74) and [RT IDs](https://github.com/uwlib-cams/sinopia_maps/blob/228f7617ce5770d256a3f278e3523e80fb235b58/xsl/001_01_storage_to_rdfxml.xsl#L30-L31).

**Comment by briesenberg07** [comment]
Thank you for taking a look at this @mcm104 ! I added a possible requirement and a couple of links to code that currently outputs RT IDs/RT IRIs differently based on selection of platform for loading. As always please don't hesitate to reach out if the code is confusing or help is needed, etc.

**Comment by mcm104** [comment]
So I have some working code: [003_batch_load_RTs.py](https://github.com/uwlib-cams/sinopia_maps/blob/main/py/003_batch_load_RTs.py) BUT I'm having a problem.

The good:
- Looks through RTs, see which ones reference which, and creates an upload order accordingly
- Uses Python requests post() to load new RTs, and uses put() to replace old RTs if something already exists at that URI, so no need to delete old RTs first
- Allows you to select which platform to upload to, and updates URIs accordingly

So I was able to load all the test RTs to production and it seemed to work, EXCEPT -- I'm getting this error if I try to use the Nomen RT: "Error retrieving TEST:UWSINOPIA:WAU:rdaNomen:na:CAMS: Cannot read properties of undefined (reading 'object')", which affects any RTs that reference Nomen. Not sure what this is trying to tell me -- is this a problem with the Nomen RT itself or something when I convert it to JSON-LD in the 003 script...?

Any ideas?

@briesenberg07

**Comment by mcm104** [comment]
Notes after 7/29 meeting:
- All test RTs successfully loaded into Sinopia Stage, BUT the Expression RT will not open; raises error: "Error retrieving TEST:UWSINOPIA:WAU:rdaExpression:monograph:CAMS: Maximum call stack size exceeded"
- Tried loading the test expression RT manually and got a JSON validation error, unsure what the problem was... need to investigate
- All other test RTs open and seem to function correctly
- PTs with multiple props not working -- turns out this is something going wrong in the XSLT. Will need to test again once XSLT is fixed.

**Comment by briesenberg07** [comment]
Closing issue because it works! Thank you @mcm104 !

**Comment by briesenberg07** [comment]
Currently attempting to use [001_output_publish_load.py](https://github.com/uwlib-cams/sinopia_maps/blob/f9bfde39d49469ba1fd04f41c0eda1732dd7f0cc/py/001_output_publish_load.py) for batch output:

- prop_set to rdf/xml
- rdf/xml to json-ld
- json-ld + Sinopia admin metadata to Sinopia via API
- prop_sets + rdf/xml RTs to HTML RTs

Still experiencing issues. Loading just now using script, received status code 200 but saw the following attempting to open RT in Sinopia Stage:

![image](https://user-images.githubusercontent.com/27664966/224461553-ced203a8-8731-45c7-96c0-e7944e6f637c.png)
![image](https://user-images.githubusercontent.com/27664966/224461559-3f67cdcd-f86f-4e7d-9943-7a617b5b694b.png)

CC @cspayne

**Comment by briesenberg07** [comment]
Note that using "Load RDF" works okay for loading a template-at-a-time, but RT IRIs must be edited if loading to STage or Development

**Comment by cspayne** [comment]
Believe I figured it out - there was an issue with when the json files were created, which was previously _before_ the iri was adjusted to include stage or development, which is why it was only working for production.
CC @briesenberg07
