### ISSUE TITLE
Avoid duplicating work in .xsl and .py

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#54]
**THE EXAMPLE WE IDENTIFIED IN THE [2022-07-29 MEETING](https://uwnetid.sharepoint.com/:w:/r/sites/og_library_cams/Shared%20Documents/sinopia_maps/meetings/[2022_meetings.docx](https://uwnetid.sharepoint.com/:w:/r/sites/og_library_cams/Shared%20Documents/sinopia_maps/meetings/2022_meetings.docx?d=w94b01f52b4fb4ae084d55a07dcc93321&csf=1&web=1&e=3y64UE)?d=w94b01f52b4fb4ae084d55a07dcc93321&csf=1&web=1&e=3y64UE)**
*There may be others?*

The [001_02 stylesheet](https://github.com/uwlib-cams/sinopia_maps/blob/1e49eeae0404c9bff6ddf1a69d2f16c55377c1dd/xsl/001_02_rt_metadata.xsl#L73-L74) constructs an RT IRI using the RT ID along with information about which platform the RT will be loaded to passed from a param:
```
[...]        
<rdf:Description
            rdf:about="{concat('https://api.', $platform, 'sinopia.io/resource/', $rt_id)}">
[...]
```
[003_batch_load_RTs.py](https://github.com/uwlib-cams/sinopia_maps/blob/1e49eeae0404c9bff6ddf1a69d2f16c55377c1dd/py/003_batch_load_RTs.py#L128-L130) reconstructs the RT IRI, using the RT ID and information about which platform the RT will be loaded to passed from a param.
```
[...]
new_URI = f"https://api.{platform}sinopia.io/resource/{RT_id}"
[...]
```

**Comment by mcm104** [comment]
Changes made in output_multiple_props branch, see commit [8a1dfcc](https://github.com/uwlib-cams/sinopia_maps/commit/8a1dfcc62aeea8cfca4c8f00235a8a695414a55a)
