### ISSUE TITLE
Fix bnode nodeID generation

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#56]
Blank node nodeID construction doesn't work for properties from the [UW RDA Extension](https://doi.org/10.6069/uwlib.55.d.4). Needs to be fixed.

# TO LOOK AT/FIX:

## Bnode construction in 001_stylesheets:
   - [001_02](https://github.com/uwlib-cams/sinopia_maps/blob/f7769ad3813015b2a9accd6f2e1d4f9a47b7a9b8/xsl/001_02_rt_metadata.xsl#L103-L105): `_order` nodeID for the first PT in the RT
- 001_03:
   - [Create `_order` nodeID for `prop_set` > `prop` being processed](https://github.com/uwlib-cams/sinopia_maps/blob/f7769ad3813015b2a9accd6f2e1d4f9a47b7a9b8/xsl/001_03_create_ordering.xsl#L28-L29)
   - [Create `_define` nodeID](https://github.com/uwlib-cams/sinopia_maps/blob/f7769ad3813015b2a9accd6f2e1d4f9a47b7a9b8/xsl/001_03_create_ordering.xsl#L30-L31)
   - [Create next `_order` nodeID](https://github.com/uwlib-cams/sinopia_maps/blob/f7769ad3813015b2a9accd6f2e1d4f9a47b7a9b8/xsl/001_03_create_ordering.xsl#L34-L35)
- 001_04:
   - [rdf:Description nodeID](https://github.com/uwlib-cams/sinopia_maps/blob/f7769ad3813015b2a9accd6f2e1d4f9a47b7a9b8/xsl/001_04_define_all_pts.xsl#L47-L48)
   - [sinopia:hasLiteralAttributes nodeID](https://github.com/uwlib-cams/sinopia_maps/blob/f7769ad3813015b2a9accd6f2e1d4f9a47b7a9b8/xsl/001_04_define_all_pts.xsl#L156-L158)
   - [sinopia:hasUriAttributes nodeID](https://github.com/uwlib-cams/sinopia_maps/blob/f7769ad3813015b2a9accd6f2e1d4f9a47b7a9b8/xsl/001_04_define_all_pts.xsl#L168-L170)
   - [sinopia:hasLookupAttributes nodeID](https://github.com/uwlib-cams/sinopia_maps/blob/f7769ad3813015b2a9accd6f2e1d4f9a47b7a9b8/xsl/001_04_define_all_pts.xsl#L180-L182)
   - [sinopia:hasResourceAttributes nodeID](https://github.com/uwlib-cams/sinopia_maps/blob/f7769ad3813015b2a9accd6f2e1d4f9a47b7a9b8/xsl/001_04_define_all_pts.xsl#L192-L195)
- 001_06: [rdf:Description `_literal_attributes` nodeID](https://github.com/uwlib-cams/sinopia_maps/blob/f7769ad3813015b2a9accd6f2e1d4f9a47b7a9b8/xsl/001_04_define_all_pts.xsl#L192-L195)
- *Likewise for [001_07](https://github.com/uwlib-cams/sinopia_maps/blob/f7769ad3813015b2a9accd6f2e1d4f9a47b7a9b8/xsl/001_07_define_uri_pts.xsl#L21-L24), [001_08](https://github.com/uwlib-cams/sinopia_maps/blob/f7769ad3813015b2a9accd6f2e1d4f9a47b7a9b8/xsl/001_08_define_lookup_pts.xsl#L24-L27), and [001_09](https://github.com/uwlib-cams/sinopia_maps/blob/f7769ad3813015b2a9accd6f2e1d4f9a47b7a9b8/xsl/001_09_define_nested_resource_pts.xsl#L22-L25)*
## Documentation:
- wiki > manage_xslt_notes provides [details on the attribute value template that generates nodeIDs](https://github.com/uwlib-cams/sinopia_maps/wiki/manage_xslt_notes#creating-blank-node-ids-in-output-rdfxml-templates); update or delete

**Comment by mcm104** [comment]
Found the problem!

[Line 24 in 001_02](https://github.com/uwlib-cams/sinopia_maps/blob/be4de8c8b198dd60a80acb24dac1038ac8ba10c9/xsl/001_02_rt_metadata.xsl#L104) selects substring after "http:", but the URIs for our extension properties is "https:". Fixed this by creating a variable that allows for http: OR https:, see <https://github.com/uwlib-cams/sinopia_maps/commit/9f3a1dfd0a4d06d01ae2d674cf09315443bd94c9>(edited further in <https://github.com/uwlib-cams/sinopia_maps/commit/b03d248461444d3c454167a10534fa7366698998>).

[Example of output.](https://github.com/uwlib-cams/sinopia_maps/blob/8169c62db6363d83f034b623ec817f7d5fdb0a40/UWSINOPIA_WAU_rdaExpression_monograph_CAMS.rdf#L418)

I did initially mess up _order vs. _define in the IDs for ordering nodes (the ones with rdf:first/rdf:rest in them), so I could use confirmation that they look correct now!

**Comment by briesenberg07** [comment]
Your example output looks right to me. 

The PT there doesn't have any literal-PT defaults, so another thing to check would be the `sinopia:hasLiteralAttributes` triple in that node, and then the object node (with nodeID ending `_literal_attributes`).

***BUT*** I see that you've already thought of this for generating [the `hasLiteralAttributes` triple nodeID](https://github.com/uwlib-cams/sinopia_maps/blob/8169c62db6363d83f034b623ec817f7d5fdb0a40/xsl/001_04_define_all_pts.xsl#L167-L180) and the [corresponding node Description](https://github.com/uwlib-cams/sinopia_maps/blob/8169c62db6363d83f034b623ec817f7d5fdb0a40/xsl/001_06_define_literal_pts.xsl#L20-L33)!! 

And that you've also covered this for `hasUriAttributes`, `hasLookupAttributes`, and `hasResourceAttributes` triples, and corresponding Descriptions.

I think we can close this issue!
