### ISSUE TITLE
combine authoring docs for the four PT types

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#60]
We are running out of room in the wiki's right-hand navigation.
The separate docs for authoring literal, uri, lookup, and nested-resource PTs can be combined.

**Comment by mcm104** [comment]
(Added draft here)[https://github.com/uwlib-cams/sinopia_maps/wiki/author_pt]

**Comment by mcm104** [comment]
Individual pages have been removed, links have been updated
