### ISSUE TITLE
Test RTs not outputting

### ISSUE THREAD

**Issue by mcm104** [uwlib-cams/sinopia_maps#64]
I added a new script [003_edit_and_load_RTs.py](https://github.com/uwlib-cams/sinopia_maps/blob/main/py/003_edit_and_load_RTs.py) that:

- Runs [001_01_storage_to_rdfxml.xsl](https://github.com/uwlib-cams/sinopia_maps/blob/main/xsl/001_01_storage_to_rdfxml.xsl)
- Replaces canonical property URIs with object/datatype URIs where applicable (see [replace_canonical_props.py](https://github.com/uwlib-cams/sinopia_maps/blob/main/py/functions/replace_canonical_props.py))
- Comments out duplicates of properties where applicable (see [fix_multi_props.py](https://github.com/uwlib-cams/sinopia_maps/blob/main/py/functions/fix_multi_props.py))
- Load RTs into Sinopia (see [batch_load_RTs.py](https://github.com/uwlib-cams/sinopia_maps/blob/main/py/functions/batch_load_RTs.py))

All of this seems to be working EXCEPT -- 001_.xsl, when run this way, is no longer outputting test RTs... unsure why this is! Will investigate more but in the meantime, any ideas @briesenberg07 ?

**Comment by briesenberg07** [comment]
I notice a couple of things:

- you don't pass in the `test` param [when running the .jar file in line 4](https://github.com/uwlib-cams/sinopia_maps/blob/e1e49e107f00e57826fb3c5c7d433d1557af87a3/py/003_edit_and_load_RTs.py#L4)
- you only run the .jar once; I think to output 'regular' *and* 'TEST' templates you'll need to run it 2X, once with *no* test param and once with

Would this do the trick?

**Comment by mcm104** [comment]
Ah, completely missed this!

[Now rectified](https://github.com/uwlib-cams/sinopia_maps/blob/8f795058a8cc8d54155c8b6f7f8320d6adeaf744/py/003_edit_and_load_RTs.py#L5), I think we're good! I'll start on documentation now.
