### ISSUE TITLE
wiki improvement needed - property_selection element guidance

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#80]
### Describe the issue

Indicate that the property_selection element must include child text so that each property available in the drop-down will have a label (will create error when loading RT if no label). See also #79 .

**Comment by cspayne** [comment]
@briesenberg07 I will make wiki updates once #79 is complete

**Comment by briesenberg07** [comment]
closed #79

**Comment by briesenberg07** [comment]
Thank you @cspayne !
![image](https://github.com/uwlib-cams/sinopia_maps/assets/27664966/250c5eeb-79fa-4f93-9b61-4915f1ce613f)
