### ISSUE TITLE
add option for all subproperties, and subproperties of subproperties, and [...] as PT prop options

### ISSUE THREAD

**Issue by briesenberg07** [uwlib-cams/sinopia_maps#94]
Currently prop_set instances offer [an option to include all subproperties](https://github.com/uwlib-cams/sinopia_maps/wiki/author_06_top_level_prop_details#enter-multiple-property-information-if-applicable) of a given property as dropdown options in a Sinopia property template. We’d like to add a further option to include all subproperties, and subproperties of subproperties, and so on, in the dropdown. This would allow us to use fewer property templates and help to limit the length of resource templates.

I’m working on XSLT to pull the needed properties from RDA-Vocabularies RDF/XML using [a call to a recursive template](https://github.com/briesenberg07/xml_stack/blob/77e67c1d7c93ea1684ce27c0baef221aabd0a0de/recursive_templates/get_rda_all_all_subproperties.xsl#L23-L53), but am so far unable to do this without duplicating properties (such as, for example, ‘[has collection registrar corporate body](https://github.com/briesenberg07/xml_stack/blob/77e67c1d7c93ea1684ce27c0baef221aabd0a0de/recursive_templates/output.xml#L81),’ which appears 15 times in my output).

**AND** update wiki guidance! See [Entering configuration info](https://github.com/uwlib-cams/sinopia_maps/wiki/author_06_top_level_prop_details#entering-configuration-info).

**Comment by briesenberg07** [comment]
📢 **Reminder**  
Need to filter out deprecated properties when bringing in subproperties for drop down to avoid [outputting deprecated properties](https://github.com/briesenberg07/xml_stack/blob/77e67c1d7c93ea1684ce27c0baef221aabd0a0de/recursive_templates/output.xml#L23)!

**Comment by briesenberg07** [comment]
Hello @cspayne 
I've made the [stylesheet updates](https://github.com/uwlib-cams/sinopia_maps/commit/ca8f2a321daa1b26516f401d22cd32fd6eec5fd6) and have a template for testing/improving post-processing
- Use RT [UWSINOPIA_WAU_rdaWork_test_ries07.rdf](https://github.com/uwlib-cams/sinopia_maps/blob/29e135a78c48e9050dfa27ab9da14eef254d1e00/UWSINOPIA_WAU_rdaWork_test_ries07.rdf) to test post-processing
   - I made sure that the template contains duplicate prop IRIs *both* within one PT and across multiple PTs
- Existing code for post-processing to remove duplicates is [in 001_output_publish_load.py](https://github.com/uwlib-cams/sinopia_maps/blob/29e135a78c48e9050dfa27ab9da14eef254d1e00/py/001_output_publish_load.py#L96-L167)
   - It may work as-is, at least for duplicate `sinopia:hasPropertyUri` triples\*\*
   - \*\*Realized while making stylesheet changes that the stylesheet will also result in many many duplicate triples as just below
   - Such duplicates may not prevent loading to Sinopia, but even if not I would like to remove these duplicate from RT triples as well. 
```
<rdf:Description rdf:about="http://rdaregistry.info/Elements/w/P10428">
      <rdfs:label xml:lang="en">has book artist person</rdfs:label>
   </rdf:Description>
[...]
 <rdf:Description rdf:about="http://rdaregistry.info/Elements/w/P10428">
      <rdfs:label xml:lang="en">has book artist person</rdfs:label>
   </rdf:Description>
```


Thank you @cspayne ! CC @pan-zhuo

**Comment by cspayne** [comment]
001_output_publish_load.py processes all subprops correctly
